// 运行时常量 - 不包含配置默认值
export const CONSTANTS = Object.freeze({
  QUEUE_SIZE: 1000,
  TOOL_TIMEOUT: 30000,
  MCP_TIMEOUT: 120000,
  MESSAGE_MAX_LENGTH: 50000,
  CHANNEL_START_TIMEOUT: 30000,
  WEBSOCKET_ACTION_TIMEOUT: 10000,
  MESSAGE_TRUNCATE_LENGTH: 500,
  IMAGE_TRUNCATE_LENGTH: 10,
  SESSION_CLEANUP_THRESHOLD: 0.9,
  MAX_IMAGE_SIZE: 10 * 1024 * 1024,
  SESSION_LOAD_BATCH_SIZE: 10,
});

// 配置默认值 - 从 config/loader.ts 读取
export const CONFIG_DEFAULTS = Object.freeze({
  DEFAULT_MAX_SESSIONS: 100,
  DEFAULT_MEMORY_WINDOW: 50,
  DEFAULT_MAX_ITERATIONS: 40,
});

export type Constants = typeof CONSTANTS;
