export {
  ConfigManager,
  configManager,
} from './config-manager.js';

export {
  FullConfigSchema,
  ServerConfigSchema,
  ProvidersConfigSchema,
  ChannelsConfigSchema,
  AgentConfigSchema,
  MemoryConfigSchema,
  MCPServerConfigSchema,
  MCPConfigSchema,
  PluginConfigSchema,
  CustomProviderSchema,
  ModelConfigSchema,
  DEFAULT_CONFIG,
  type FullConfig,
  type ServerConfig,
  type ProvidersConfig,
  type ChannelsConfig,
  type AgentConfig,
  type MemoryConfig,
  type CustomProvider,
  type ModelConfig,
  type MCPServerConfig,
  type MCPConfig,
  type PluginConfig,
} from './schema.js';
